// Machine-derived samurai-mask pixel grids — do NOT hand-edit.
// Provenance: reference AVIF -> sips PNG/BMP -> per-cell downsample of the 626px art
// (dominant-color for SPLASH crisp detail; foreground-average for SMALL/TINY so the
// silver face survives at low res) -> median-cut palette. Extraction tooling lives in
// the session scratchpad (dev-time only, not shipped).
//
// Rendered by src/banner.js with UNICODE half-blocks (U+2580 top / U+2584 bottom),
// two vertical pixels per character row, each pixel its own colour. 'palette' holds the
// image-true RGB; banner.js applies a dark-terminal colour grade at render time and,
// on Apple_Terminal (which mangles 24-bit truecolour), maps to xterm-256. '.' = transparent.
//
// SPLASH 76x78 (39 rows) — startup hero, shown once.
// SMALL  20x20 (10 rows) — everyday welcome accent.
// TINY   12x12 (6 rows) — prompt snippet.

export const SPLASH = {
  w: 76, h: 78,
  chars: 'KDSWGORXMBCEFHJLNPQTUVYZabcdefghijkl',
  palette: [[7,7,6], [102,23,22], [97,64,65], [122,35,36], [147,41,38], [168,107,30], [213,63,13], [208,46,38], [240,100,78], [189,119,27], [189,119,29], [188,120,31], [165,121,62], [128,128,121], [192,120,30], [242,183,36], [243,137,80], [250,120,108], [250,122,108], [247,123,107], [248,228,121], [249,228,123], [250,229,123], [249,231,122], [253,119,105], [252,121,106], [252,122,105], [253,122,107], [253,123,105], [254,123,106], [251,227,124], [252,229,122], [252,230,122], [150,149,146], [250,230,129], [222,221,216]],
  rows: [
    '.............KK..............................................KK.............',
    '............KiK..............................................KKK............',
    '............KiK..............................................KiKK...........',
    '............KhK..............................................KiKK...........',
    '...........KYiK..............................................KYiKK..........',
    '...........KYgK....................KKKKKK....................KYYZK..........',
    '...........KYgYK..................KdddbbPKK.................KZYYZK..........',
    '..........KZgghK...............KKKKbPWWWPKKKK...............KhkZYKK.........',
    '..........KgghZKK..............KKKKbWWWWPKKKKK..............KZkZkZK.........',
    '..........KhYkLhK...........KKKjjjKbWWWWbKjjjjKK...........KUgLZkZK.........',
    '..........KBYkLhK........KKKHHHKKKKaWWWWaKKKKKHHKKK........KVgLYkKK.........',
    '..........KBYhhhhKK.....KKHHKKKSSKKaWWWWaKSSSKKKHHHK......KYVgkkCKK.........',
    '..........KBEYVNiKK....KHHHKSSSSSKKdWWWWaKSSSSSSKHHHK.....KkLkkgCKK.........',
    '..........KBJYYNZZZK..KHHKKSSSSSSKKdWWWWaKSSSSSSSKKHHK...KYYLkkCCKK.........',
    '..........KBJYYYNYZiKKHHKSSSSSSSKKKdWWWWaKKSSSSSSSSKHHKKKZYLkkCCCKK.........',
    '..........KKEJVYZLZYYVKKKSSSSSSKKKcaaWWWabdKKSSSSSSSKKYYYVLkkCCCKK..........',
    '...........KEJJEYYkkgYhKKSSSSSKKKcaaaaaaaaaKKKSSSSSSKiYYgVLkBCCCKK..........',
    '............KJCJEkkkJihKSSKKKKKKKcWWWWWWWWbKKKKKSSSSKiZYYkkBBCCK............',
    '............KJCJBBZVYiKSKKKKKKKKKcWWWWWWWWaKKKKKKKSSSKJJZYCCCCBK............',
    '............KJCJBBCCJKSKKKKKKKKKKcWWWKKWWWaKKKKKKKKKSSKBBCCCCBBK............',
    '.............KJBBBBKKSKKKKKKKKKKKcWWKhZKWWaKKKKKKKKKKSSKBBCCBBK.............',
    '..............KKBBBKKSKKKKKKKKKKaWWKiKKhKWWdKKKKKKKKKKKSKBBBBK..............',
    '...............KKCKKKKKKKKKKKKKcWWKiYiKYYKWWaKKKKKKKKKKSSKJJK...............',
    '................KKSKKKKKKKKKKKKaWKhYYiiYZVKWbaKKKKKKKKKKKKKK................',
    '.................KKKKKKKKKKKKKbWKhYYRiiKYYZKWPPKKKKKKKKKKKK.................',
    '.................KKKKKKKKKKKeaWWKKKKlKKlKKKKWWdPKKKKKKKKKKK.................',
    '.................KKKKKKKKKKaaWWWKKJRRRRRRRRKWWWPKKKKKKKKKKKK................',
    '...............KKKKKKKKKKKKTWWWWKRJJKRRKRRJKWWWWPPPPPPPPQKDKKK..............',
    '.........KKKKKKaKKKfbaaaaaaWWWWWKRRKRKKRKRGKWWWWPbccccccaDDDKKKKKKKK........',
    '.........KdaaabaaaaKKWWWWWWWWWWWWKKBKKOKJGKWWWWWWWWWWWWWWKKKcaaaaaKK........',
    '.........KWWWWWWbaaKKKWKKWWWWWWWWWKKKRRRKKWWWWWWWWWWWWKKKPQPQWWWWWK.........',
    '..........KWWWWWWWPbbbKKKKWWWWWWWWWKKKKKKWWWWWWWWWWKKKPPPPWWWWWWWK..........',
    '...........KWWWWWWWWWbaabbKKWWWWWWWWKKKKWWWWWWWWKKKbaaWWWWWWWWWWK...........',
    '............KKKKKKKKKKKKKKbPKKKWWWWWWWWWWWWWWKKKbcaKKKKKKKKKKKKK............',
    '...............KKDDDDDDDDDKKMMMKKKWWWWWWWWWDDMMMKDDDDDDDDDDDK...............',
    '..............KKKKKKKKKKKKWWKKKKKWWWWWWWWWKKKKMKKKKKKKKDDDDDKK..............',
    '..............KaaKDDKKHHKKKKKKKWWWKKKKKKKKKXXKKKKKKSSKKKDDDWTKK.............',
    '.............KaPWKDDKKHHHKKKKKKKKKWWWWWWWWWKKKKKKKKSSSSKKWDWbaK.............',
    '............KKaDKKDKKHKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKSKKWDWWbbK............',
    '...........KKKGDDDKKKKKKKKKLLLLKKKKKKKKKKKKKKKJJJKKKKKSSKKDWWDcKK...........',
    '...........KKKDDDDKKHKlKKKKKLLLKKKKKKKKKKKKKYYYYKKKKKlKHHKDDDDDKK...........',
    '..........KKaaKKKDKKHKKKKKKKLLLLLKKKKKKKKKKKiikiKKKKjlHHHKDDKKabaK..........',
    '.........KXaaMMKKDKKHHHKKKKKKKKKKKSKSSSSKKKKKKKKKKKHHHHHHKKDKGcaaKK.........',
    '.........KbPGGGDDKKKHHHKljKKKKKKKSSKSSSSKKKKKKKKKllHHHHKHKKDDGGabbaK........',
    '........KddGGGGDDKKHKKHHHllllKKKSSSKHHHHKKHlKKKllllKHHHHHKKDDDGGPaaK........',
    '........KeTGGGKKDKKHHlKllKKKKlllllKKHHHHKKHlljHHKKKlHHKHHKKWDDDGGddaK.......',
    '........KaGGGDKKKKKKHHHKlllllllHHKHKjjjjKKKHllljlllHHKHHSKKKKDDGGGeaK.......',
    '........KKDDDDKKKKKKKlllKKjjjjjHKHlKllllKHHKKllllllKKHHKKKKKKDDDDDDKK.......',
    '......KKbaKKKKWKKKKHKKHlllllKKKKKHHHllllHHHKKKKHHlllllHKSKKSKGDKKKaaaK......',
    '.....KdbXXcaaKWKKKKHKKHHHHlHKSSSKHHHllllHHHKSSKKHHlllHKSSKKSKGKdbbaabdK.....',
    '....KbPaXXWWWKKKKKKKHKKHHHHKSSHHKKKKjjjjKKKKKSSKKHHlHKSSSKKSKGKbQQGGPddK....',
    '....KaaXXXWWWDKKKKKKHHHKKKKKSHKK.KKKKjjKKKK.KHHSSKKKKSHHjKKSKKKDGGGGGPdKK...',
    '....KaXXXWWWDDKKKKKKHHHHSSSSSKKlKlKKKKKKKKlKHKHHSSSSSSjjKKKSSKWDDGGGGGbKK...',
    '...KYKXXWWWKDKKKKKKKKHHHHSHHKKllllllKKKKlllljlKHHSSSjjHKKKKKKKKDDGGGGGKihK..',
    '.KKZhhKWWWWKDKKKKKKKKKHHHHHlKlllllllllKllllllllKHHljlKKKKKKKKSKDKGGGGKYkYiK.',
    'KECkkhLKKWKKDKKKKKKKKKKHHHlKKKKKKKKKKKKKKKKKKKKKKHlllKSKKKKKKSKGKKGKKKUkYYZK',
    'KKEEELLLLKKKDKKKKKKKWWKKHHjKKKK...K..KK..K...KKKKjljHKSKKKKKKSKGKKKLLLLLLCBK',
    '.KKOOEEEENNNKKKKKKKKWWKKKHlKKKKK.KKKKKKKKKK.KKKKK..KKKSKKKKKKSKKJEEBBBBBBKK.',
    '..KKKOOOOOOOOKKKKKKKKWWKKKKKKXKK.KKKKKKKKKK.KKKKKKKKSSSKKKKKKSKOOOOOOOOOKK..',
    '....KKKOOOOOOKKKKKKKKKWWKKKKKXXKKKKKKKKKKKKKKXXKKKKKSSKKKKKKKSKOOOOOOKKK....',
    '.......KKOOOOKKKKKKKWWKWWKKKKXXKKXXXKXXKXXXKXXXKK.KSSKKKKKKKKSKOOOOKKK......',
    '.........KKOOKKKKKK.WWWKWWK.KKXXKXXXKXXXKXXKXXXK..KSKKWK.KKKKSKOOKKK........',
    '...........KKKKKK...KWWWKKK..KXXKXXKKKXKKXKKXXK..HKKWGKK...KKSKKK.K.........',
    '...........KKKKS.....KKWWKKHHlKKKKKK.KKKKKK.KK..HHKWWKK.....KSKKK...........',
    '.............KKK......KKWWKKHllK..K..KK..K..K..HKKKWKK......KKK.............',
    '..............KK.......KKWWKHHlKKKKKKKKKKKKKllHHKWWKK.......KK..............',
    '........................KKWWWHHHlllllllllllllHHKWWKK........................',
    '.........................KKWWKKHHllHKKKKKjllHHWWWKK.........................',
    '..........................KKWWKKHHKWMMMMGKHHHWWWKK..........................',
    '...........................KKWWKKHWWMMMMGGKKKWWKK...........................',
    '............................KKWWKWWWKKKKGGGKKWKK............................',
    '.............................KKWWWWWKKKKKGGGKKK.............................',
    '..............................KKWWWKMMMMKGGGKK..............................',
    '...............................KKKKWMMMMMKKKK...............................',
    '................................KKKWWWWWWWKK................................',
    '.................................KKKWWWWWKK.................................',
    '..................................KKWWWWKK..................................',
    '...................................KKKKKK...................................',
  ],
};
export const SMALL = {
  w: 20, h: 20,
  chars: 'KDSWGORXMBCE',
  palette: [[32,24,23], [75,29,23], [78,70,65], [107,47,38], [139,54,47], [114,95,65], [119,116,113], [147,98,37], [203,152,64], [155,132,118], [200,169,84], [206,180,108]],
  rows: [
    '...S............S...',
    '...C.....GG.....C...',
    '..SEO..SSGGSS...EO..',
    '...CEOSKKGGKKS.CMW..',
    '...XMCKKDGGWKKCMX...',
    '....XKKKWOOWKKKX....',
    '....KKKWWMMGWKKK....',
    '..DGGGGWWGXWGGGGGW..',
    '...DDWWWWWWWWWDDD...',
    '...GDKKKKDDDKKKDG...',
    '...WKSKXWKKKXKRKW...',
    '..GGKOBRRSSRRRRKGX..',
    '..GDKSBRSBBSRBSKDG..',
    '.XGDKSSSRSSROOSKDGX.',
    'XMXKKKOSSKKSKRKKKWMX',
    '..XWKDDDDDDDDKKKDXW.',
    '...K..DRSSSSOD..K...',
    '.......DRXXRD.......',
    '........DWGD........',
    '.........DD.........',
  ],
};
export const TINY = {
  w: 12, h: 12,
  chars: 'KDSWGORXM',
  palette: [[32,19,18], [70,25,23], [69,56,54], [119,55,40], [114,97,57], [107,106,104], [133,101,85], [164,130,64], [203,160,72]],
  rows: [
    '............',
    '..M.SWWS.M..',
    '..MGKWWKGM..',
    '..WKDRRDKW..',
    '..WWWWWWWW..',
    '..DDDDDDKD..',
    '..DSGSKGOD..',
    '.WKOOOOOOKW.',
    'XWKSOOSSSKWX',
    '.GKDWDDDKKW.',
    '....SRRS....',
    '.....DW.....',
  ],
};
