// Machine-derived samurai-mask pixel grids — do NOT hand-edit.
// Provenance: reference AVIF -> sips PNG/BMP -> per-cell downsample of the 626px art
// (dominant-color for SPLASH crisp detail; foreground-average for SMALL so the
// silver face survives at low res) -> median-cut palette. Extraction tooling lives in
// the session scratchpad (dev-time only, not shipped).
//
// Rendered by src/banner.js with UNICODE half-blocks (U+2580 top / U+2584 bottom),
// two vertical pixels per character row, each pixel its own colour. 'palette' holds the
// image-true RGB; banner.js applies a dark-terminal colour grade at render time and,
// on Apple_Terminal (which mangles 24-bit truecolour), maps to xterm-256. '.' = transparent.
//
// SPLASH 76x78 (39 rows) — startup hero, shown once.
// SMALL  24x24 (12 rows) — narrow-terminal fallback.

export const SPLASH = {
  w: 76, h: 78,
  chars: 'KDSWGORXMBCEFHJLNPQTUVYZabcdefghijkl',
  palette: [[7,7,6], [102,23,22], [97,64,65], [122,35,36], [147,41,38], [168,107,30], [213,63,13], [208,46,38], [240,100,78], [189,119,27], [189,119,29], [188,120,31], [165,121,62], [128,128,121], [192,120,30], [242,183,36], [243,137,80], [250,120,108], [250,122,108], [247,123,107], [248,228,121], [249,228,123], [250,229,123], [249,231,122], [253,119,105], [252,121,106], [252,122,105], [253,122,107], [253,123,105], [254,123,106], [251,227,124], [252,229,122], [252,230,122], [150,149,146], [250,230,129], [222,221,216]],
  rows: [
    '.............KK..............................................KK.............',
    '............KiK..............................................KKK............',
    '............KiK..............................................KiKK...........',
    '............KhK..............................................KiKK...........',
    '...........KYiK..............................................KYiKK..........',
    '...........KYgK....................KKKKKK....................KYYZK..........',
    '...........KYgYK..................KdddbbPKK.................KZYYZK..........',
    '..........KZgghK...............KKKKbPWWWPKKKK...............KhkZYKK.........',
    '..........KgghZKK..............KKKKbWWWWPKKKKK..............KZkZkZK.........',
    '..........KhYkLhK...........KKKjjjKbWWWWbKjjjjKK...........KUgLZkZK.........',
    '..........KBYkLhK........KKKHHHKKKKaWWWWaKKKKKHHKKK........KVgLYkKK.........',
    '..........KBYhhhhKK.....KKHHKKKSSKKaWWWWaKSSSKKKHHHK......KYVgkkCKK.........',
    '..........KBEYVNiKK....KHHHKSSSSSKKdWWWWaKSSSSSSKHHHK.....KkLkkgCKK.........',
    '..........KBJYYNZZZK..KHHKKSSSSSSKKdWWWWaKSSSSSSSKKHHK...KYYLkkCCKK.........',
    '..........KBJYYYNYZiKKHHKSSSSSSSKKKdWWWWaKKSSSSSSSSKHHKKKZYLkkCCCKK.........',
    '..........KKEJVYZLZYYVKKKSSSSSSKKKcaaWWWabdKKSSSSSSSKKYYYVLkkCCCKK..........',
    '...........KEJJEYYkkgYhKKSSSSSKKKcaaaaaaaaaKKKSSSSSSKiYYgVLkBCCCKK..........',
    '............KJCJEkkkJihKSSKKKKKKKcWWWWWWWWbKKKKKSSSSKiZYYkkBBCCK............',
    '............KJCJBBZVYiKSKKKKKKKKKcWWWWWWWWaKKKKKKKSSSKJJZYCCCCBK............',
    '............KJCJBBCCJKSKKKKKKKKKKcWWWKKWWWaKKKKKKKKKSSKBBCCCCBBK............',
    '.............KJBBBBKKSKKKKKKKKKKKcWWKhZKWWaKKKKKKKKKKSSKBBCCBBK.............',
    '..............KKBBBKKSKKKKKKKKKKaWWKiKKhKWWdKKKKKKKKKKKSKBBBBK..............',
    '...............KKCKKKKKKKKKKKKKcWWKiYiKYYKWWaKKKKKKKKKKSSKJJK...............',
    '................KKSKKKKKKKKKKKKaWKhYYiiYZVKWbaKKKKKKKKKKKKKK................',
    '.................KKKKKKKKKKKKKbWKhYYRiiKYYZKWPPKKKKKKKKKKKK.................',
    '.................KKKKKKKKKKKeaWWKKKKlKKlKKKKWWdPKKKKKKKKKKK.................',
    '.................KKKKKKKKKKaaWWWKKJRRRRRRRRKWWWPKKKKKKKKKKKK................',
    '...............KKKKKKKKKKKKTWWWWKRJJKRRKRRJKWWWWPPPPPPPPQKDKKK..............',
    '.........KKKKKKaKKKfbaaaaaaWWWWWKRRKRKKRKRGKWWWWPbccccccaDDDKKKKKKKK........',
    '.........KdaaabaaaaKKWWWWWWWWWWWWKKBKKOKJGKWWWWWWWWWWWWWWKKKcaaaaaKK........',
    '.........KWWWWWWbaaKKKWKKWWWWWWWWWKKKRRRKKWWWWWWWWWWWWKKKPQPQWWWWWK.........',
    '..........KWWWWWWWPbbbKKKKWWWWWWWWWKKKKKKWWWWWWWWWWKKKPPPPWWWWWWWK..........',
    '...........KWWWWWWWWWbaabbKKWWWWWWWWKKKKWWWWWWWWKKKbaaWWWWWWWWWWK...........',
    '............KKKKKKKKKKKKKKbPKKKWWWWWWWWWWWWWWKKKbcaKKKKKKKKKKKKK............',
    '...............KKDDDDDDDDDKKMMMKKKWWWWWWWWWDDMMMKDDDDDDDDDDDK...............',
    '..............KKKKKKKKKKKKWWKKKKKWWWWWWWWWKKKKMKKKKKKKKDDDDDKK..............',
    '..............KaaKDDKKHHKKKKKKKWWWKKKKKKKKKXXKKKKKKSSKKKDDDWTKK.............',
    '.............KaPWKDDKKHHHKKKKKKKKKWWWWWWWWWKKKKKKKKSSSSKKWDWbaK.............',
    '............KKaDKKDKKHKKKKKLKKKKKKKKKKKKKKKKKKKKKKKKKKSKKWDWWbbK............',
    '...........KKKGDDDKKKKKKKKKLLLLKKKKKKKKKKKKKKKJJJKKKKKSSKKDWWDcKK...........',
    '...........KKKDDDDKKHKlKKKKKLLLKKKKKKKKKKKKKYYYYKKKKKlKHHKDDDDDKK...........',
    '..........KKaaKKKDKKHKKKKKKKLLLLLKKKKKKKKKKKiikiKKKKjlHHHKDDKKabaK..........',
    '.........KXaaMMKKDKKHHHKKKKKKKKKKKSKSSSSKKKKKKKKKKKHHHHHHKKDKGcaaKK.........',
    '.........KbPGGGDDKKKHHHKljKKKKKKKSSKSSSSKKKKKKKKKllHHHHKHKKDDGGabbaK........',
    '........KddGGGGDDKKHKKHHHllllKKKSSSKHHHHKKHlKKKllllKHHHHHKKDDDGGPaaK........',
    '........KeTGGGKKDKKHHlKllKKKKlllllKKHHHHKKHlljHHKKKlHHKHHKKWDDDGGddaK.......',
    '........KaGGGDKKKKKKHHHKlllllllHHKHKjjjjKKKHllljlllHHKHHSKKKKDDGGGeaK.......',
    '........KKDDDDKKKKKKKlllKKjjjjjHKHlKllllKHHKKllllllKKHHKKKKKKDDDDDDKK.......',
    '......KKbaKKKKWKKKKHKKHlllllKKKKKHHHllllHHHKKKKHHlllllHKSKKSKGDKKKaaaK......',
    '.....KdbXXcaaKWKKKKHKKHHHHlHKSSSKHHHllllHHHKSSKKHHlllHKSSKKSKGKdbbaabdK.....',
    '....KbPaXXWWWKKKKKKKHKKHHHHKSSHHKKKKjjjjKKKKKSSKKHHlHKSSSKKSKGKbQQGGPddK....',
    '....KaaXXXWWWDKKKKKKHHHKKKKKSHKK.KKKKjjKKKK.KHHSSKKKKSHHjKKSKKKDGGGGGPdKK...',
    '....KaXXXWWWDDKKKKKKHHHHSSSSSKKlKlKKKKKKKKlKHKHHSSSSSSjjKKKSSKWDDGGGGGbKK...',
    '...KYKXXWWWKDKKKKKKKKHHHHSHHKKllllllKKKKlllljlKHHSSSjjHKKKKKKKKDDGGGGGKihK..',
    '.KKZhhKWWWWKDKKKKKKKKKHHHHHlKlllllllllKllllllllKHHljlKKKKKKKKSKDKGGGGKYkYiK.',
    'KECkkhLKKWKKDKKKKKKKKKKHHHlKKKKKKKKKKKKKKKKKKKKKKHlllKSKKKKKKSKGKKGKKKUkYYZK',
    'KKEEELLLLKKKDKKKKKKKWWKKHHjKKKK...K..KK..K...KKKKjljHKSKKKKKKSKGKKKLLLLLLCBK',
    '.KKOOEEEENNNKKKKKKKKWWKKKHlKKKKK.KKKKKKKKKK.KKKKK..KKKSKKKKKKSKKJEEBBBBBBKK.',
    '..KKKOOOOOOOOKKKKKKKKWWKKKKKKXKK.KKKKKKKKKK.KKKKKKKKSSSKKKKKKSKOOOOOOOOOKK..',
    '....KKKOOOOOOKKKKKKKKKWWKKKKKXXKKKKKKKKKKKKKKXXKKKKKSSKKKKKKKSKOOOOOOKKK....',
    '.......KKOOOOKKKKKKKWWKWWKKKKXXKKXXXKXXKXXXKXXXKK.KSSKKKKKKKKSKOOOOKKK......',
    '.........KKOOKKKKKK.WWWKWWK.KKXXKXXXKXXXKXXKXXXK..KSKKWK.KKKKSKOOKKK........',
    '...........KKKKKK...KWWWKKK..KXXKXXKKKXKKXKKXXK..HKKWGKK...KKSKKK.K.........',
    '...........KKKKS.....KKWWKKHHlKKKKKK.KKKKKK.KK..HHKWWKK.....KSKKK...........',
    '.............KKK......KKWWKKHllK..K..KK..K..K..HKKKWKK......KKK.............',
    '..............KK.......KKWWKHHlKKKKKKKKKKKKKllHHKWWKK.......KK..............',
    '........................KKWWWHHHlllllllllllllHHKWWKK........................',
    '.........................KKWWKKHHllHKKKKKjllHHWWWKK.........................',
    '..........................KKWWKKHHKWMMMMGKHHHWWWKK..........................',
    '...........................KKWWKKHWWMMMMGGKKKWWKK...........................',
    '............................KKWWKWWWKKKKGGGKKWKK............................',
    '.............................KKWWWWWKKKKKGGGKKK.............................',
    '..............................KKWWWKMMMMKGGGKK..............................',
    '...............................KKKKWMMMMMKKKK...............................',
    '................................KKKWWWWWWWKK................................',
    '.................................KKKWWWWWKK.................................',
    '..................................KKWWWWKK..................................',
    '...................................KKKKKK...................................',
  ],
};
export const SMALL = {
  w: 24, h: 24,
  chars: 'KDSWGORXMBCEFHJL',
  palette: [[4,3,3], [83,25,26], [119,33,36], [83,42,43], [115,115,113], [155,73,34], [214,108,44], [227,127,70], [190,189,184], [250,121,107], [224,222,208], [249,230,124], [223,222,217], [252,120,107], [251,229,124], [251,230,124]],
  rows: [
    '....K..............K....',
    '...KJ..............LK...',
    '...JJ.....KHSK.....EE...',
    '...RJK..KWKSSKWK..KER...',
    '...KEEJKWWWSSKWWGLERR...',
    '....RRJKKKHSSKKKWERR....',
    '....KRKKKKSSSSKKKWRR....',
    '.....KKKKHKLEKSKKKK.....',
    '....KKKKSSKORKSHKBKKK...',
    '...SSHHSSSSKKSSSSHBSS...',
    '....KKKKKKSSSSKHKKDK....',
    '....HKKKKKKKKKKKKKDH....',
    '...KDKKKKXKKKKKKKGKKK...',
    '...HSKGGKKGGGKKCGGKSH...',
    '..KSKKGFFFGMMGCCCGKDSK..',
    '.KHSKKKGKGKKMKGKCGKKHHK.',
    '.LSSKKKGGKCKKCCGGKKKDSL.',
    'KRXKKKKKKKKKKKKKKKKKKRRK',
    '..OOKKKSKKKKKKKKWKKKOO..',
    '....K..KKKKKKKKKS..K....',
    '........SGCKKFGS........',
    '.........SKXXKS.........',
    '..........KHHK..........',
    '...........KS...........',
  ],
};
